{
 "title": "Digital_Twin_Dashboard_Grafana",
 "time": { "from": "2024-12-31T23:00:00.000Z", "to": "2025-01-01T23:00:00.000Z" },
 "panels": [
  { "title": "MAIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EPFL Spacecraft Logo",
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "<div style='display:flex;justify-content:center;align-items:center;height:100%;'><img src='https://cdn.prod.website-files.com/63dac4eefd38bf794d1d9ba8/63dbb42704e717834f745b45_EPFL%20Spacecraft-%20logo-6.png' style='max-width:100%;max-height:100%;object-fit:contain;'/></div>"
   }
  },
  {
   "title": "Current Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Globe visualisation",
   "type": "flaminggoat-maptrack3d-panel",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"timestamp\" as time, \"Lat\", \"Lng\", \"altitude\", \"eclipse\"\nFROM \"satellite_data\"\n",
     "select": [
      [
       { "params": [ "Lat" ], "type": "field" }
      ],
      [
       { "params": [ "Lng" ], "type": "field" }
      ],
      [
       { "params": [ "altitude" ], "type": "field" }
      ],
      [
       { "params": [ "eclipse" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global positioning ",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"Lat\", \"Lng\" FROM \"satellite_data\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Lat" ], "type": "field" }
      ],
      [
       { "params": [ "Lng" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "satellite_data",
     "query": "SELECT \"latitude\", \"longitude\" FROM \"satellite_data\"",
     "select": [
      [
       { "params": [ "Lat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Lng" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Orbit parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"time\", \"altitude\"\nFROM \"NICE\".\"autogen\".\"satellite_data\"\nWHERE time >= 0\n",
     "select": [
      [
       { "params": [ "altitude" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AOP",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "radian" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"time\", \"eclipse\", \"battery\"\nFROM \"NICE\".\"autogen\".\"satellite_data\"\nWHERE time >= 0",
     "select": [
      [
       { "params": [ "AOP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ECC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"time\", \"altitude\"\nFROM \"NICE\".\"autogen\".\"satellite_data\"\nWHERE time >= 0\n",
     "select": [
      [
       { "params": [ "ECC" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inclination",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "radian" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "query": "SELECT \"time\", \"altitude\"\nFROM \"NICE\".\"autogen\".\"satellite_data\"\nWHERE time >= 0\n",
     "select": [
      [
       { "params": [ "INC" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last power value",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "satellite_data",
     "query": "SELECT last(\"batt_vbatt\") /1000 FROM /^$suid$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 10000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power generation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "generation" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "eclipse" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power consumption ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar cells efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "solar_cells_efficiency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "MODES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Mode view",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "modes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mode repartition",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode::tag" ], "type": "tag" }
     ],
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "modes" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "visible::tag" ], "type": "tag" }
     ],
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mode view",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 56 },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "modes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "modes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "DATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Visibility",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data GNSS TOF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "data_GNSS_TOF" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data HK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "measurement": "satellite_data",
     "select": [
      [
       { "params": [ "data_HK" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}